# Generated by Django 5.1.8 on 2025-04-17 11:30

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_verified_user_is_active_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='business_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='business_logo',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='business_address',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='email',
            field=models.EmailField(default='', max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='line1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='line2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
